config/routes.rb
Fma2::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  root :to => "home#index"  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/image.rb
class Image < ActiveRecord::Base
  validates :name, :url, :thumbnail, :presence => true
  has_many :related_images, :dependent => :destroy
  has_many :vendors, :through => :related_images
  
end

app/models/related_image.rb
class RelatedImage < ActiveRecord::Base
  belongs_to :vendor
  belongs_to :image
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  validates :name, :presence => true

  has_and_belongs_to_many :categories
  has_many :related_images, :dependent => :destroy, :order => 'rank'
  has_many :images, :through => :related_images
  
  accepts_nested_attributes_for :related_images, :allow_destroy => true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/admin/image_utility_helper.rb
module Admin::ImageUtilityHelper
  
require "net/http"
require "uri"
require "digest/md5"
require "rexml/document"

  
  class XmlFlickrObj
    API_KEY = '8f7cc5f3e11452db7f1aa51361c1e04a'
    METHOD = 'flickr.people.getPublicPhotos'
    USER_ID = '43313252@N02'
    attr_accessor :numItems, :currentPage
    attr_reader :totalPages, :doc
    def initialize(attrhsh = {})
      if (attrhsh.has_key?(:numItems))
        @numItems = attrhsh[:numItems]
      end
      if (attrhsh.has_key?(:currentPage))
        @currentPage = attrhsh[:currentPage]
      end
      xml = get_flickr_xml();
      @doc = REXML::Document.new(xml)
      @totalPages = REXML::XPath.first(doc,'/rsp/photos/@pages')
      puts "totalpages = #{@totalPages} "
    end
    def display_each_item () 
      tmp = ""
      @doc.elements.each('rsp/photos/photo') do |el|
        #yield(el.attributes['url_m'],el.attributes['title'],el.attributes['url_t'])
        yield(el)
      end
    end
    
       
    def get_pagination_html 
      #uri = request.env['PATH_INFO']
      puts caller.methods;
      #uri = helper
      #html = ""
=begin      
      for i in 1..@total_pages do
        if (@current_page != i)
          html << "<a href='#{uri}'>#{i}</a>"
        else 
          html << i
        end
        
    
      end
      html
=end      
   end    
    
    private 
    def get_flickr_xml()
     request ="http://api.flickr.com/services/rest/?method=#{METHOD}&user_id=#{USER_ID}&extras=url_t,url_l&api_key=#{API_KEY}"
     if (@currentPage != nil)
       request << "&page=#{@currentPage}"
     end
     if (@numItems != nil)
       request << "&per_page=#{@numItems}"
     end
      puts request
      response = Net::HTTP.get_response(URI.parse(request)).body;
      
     
   
     
    end
 
  end
 
  
 
  
 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for(["admin",@category],:remote => remote,:format => format,:html=>{:id => 'create_category_form'}) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="validation-error">
  </div>  
  <div class="field"> 
    <%= f.label :parent %> <br/>


    <%= f.select(:parent_id,options_for_select(@parent_categories_options,@default_parent_option))%>
      <!--%=get_cat_opt%-->
  
  </div> 
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :short_description %><br />
    <%= f.text_field :short_description %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/categories/_item.html.erb
<tr class="cat-item" id="tag-<%=category.id%>">
  <td class="cell-name">
    <strong>
      <%=link_to raw("&#8212") * level + category.name, edit_admin_category_path(category) , :class=>'edit-link' %>
    </strong>
    <div class="item-action">
      <%=link_to "edit", edit_admin_category_path(category) %> |
      <a class="quick-edit" href="#">Quick Edit</a> |
      <%= link_to 'Destroy', [:admin,category], :confirm => 'Are you sure?', :method => :delete %>
    </div>
    <div class="hidden data">
      <div class="name"><%=category.name%></div>
      <div class="short-description"><%=category.short_description%></div>
      <div class="id"><%=category.id%></div>

    </div>  
  </td>
  <td><%=category.short_description%></td>
  <td><%=category.id%></td>
</tr>

app/views/admin/categories/_map.html.erb
<table id="map">
<%= raw get_map 2%>
</table>  

app/views/admin/categories/edit.html.erb
<h1>Editing category</h1>

<%= render :partial=>'form' ,:locals=>{:remote=>false,:format=>'html'}%>

<%= link_to 'Show', [:admin,@category] %> |
<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/index.html.erb
<h1>New category</h1>

<div class="category wrap">
  <div class="left">
    <%= render :partial=>'form' ,:locals=>{:remote=>true,:format=>'json'}%>
    <%= link_to 'Back', admin_categories_path %>

  </div>
  <div class="right">
    <form id="index-form">
    <table id="map">
      <tr id="tag-">
        <th>
          Name
        </th>
        <th>
          Description
        </th>
        <th>
           Id
        </th>
        
      </tr>
     <%=loop_all_categories do |category,level| %>
        <%= render :partial => "item", :locals => { :level => level, :category=>category } %>
     <%end%>  
  
    </table>
    </form>  
  </div>
</div>

    <form class="hidden" id="quick-edit-form">
      <table>
      <tr class="inline-edit">
        <td colspan="3">
          <label for="category_name">Name</label><input type="text" name="category_name">
          <br/>
          <label for="category_short_description">Short Description</label><input type="text" name="category_short_description">
          <br />
          <input type="button" value="Cancel"> <input type="button" value="Submit">
        </td> 
      </tr>
      </table>
    </form>  

app/views/admin/categories/new.html.erb
<h1>New category</h1>

<div class="category wrap">
  <div class="left">
    <%= render 'form' %>
    <%= link_to 'Back', admin_categories_path %>

  </div>
  <div class="right">
    <table id="map">
      <tr>
        <th>
          Name
        </th>
        <th>
          Description
        </th>
        <th>
           Id
        </th>
        
      </tr>
   <%=process_category(Category.find(2)) do |category,level| %>
      <%= render :partial => "item", :locals => { :level => level, :category=>category } %>
  <%end%>  
    </table>
    <form id="hidden">
      <table>
      <tr>
        <td colspan="3">
          <label for="category_name">Name</label><input type="text" name="category_name">
          <label for="category_short_description">Short Description</label><input type="text" name="category_short_description">
          <input type="button" value="Cancel"> <input type="submit" value="submit">
        </td> 
      </tr>
      </table>
    </form>  

  </div>
</div>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Short description:</b>
  <%= @category.short_description %>
</p>



<%= link_to 'Edit', edit_admin_category_path(@category) %> |
<%= link_to 'Back', admin_categories_path %>

app/views/admin/image_utility/index.html.erb
<h1>Listing Recent Flickered Image</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @flick.doc.elements.each('rsp/photos/photo') do |image| %>

  <tr>
    <td><img src="<%= image.attributes['url_t'] %>"/></td>
    <td><%=image.attributes['title']%></td>
    <td><form class="image-utility-form" action="/admin/images.json" data-remote="true" method="post">
       Name <input type="text" name="image[name]"/>
       Short Description <input type="text" name="image[short_description]"/>
       <input type="hidden" name="image[url]" value="<%=image.attributes['url_l']%>"/>
       <input type="hidden" name="image[thumbnail]" value="<%=image.attributes['url_t']%>"/>

       <input type="submit" value="Add to Image Index"/>
      </form>
    </td>

</td>
  </tr>
<% end %>
 
</table>

<br />

app/views/admin/images/_form.html.erb
<%= form_for(["admin",@image]) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :short_description %><br />
    <%= f.text_field :short_description %>
  </div>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :thumbnail %><br />
    <%= f.text_field :thumbnail %>
  </div>

  <%  unless @image.blank? %>
<img src="<%=@image.url%>"/>
  <%end%>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin,@image] %> |
<%= link_to 'Back', admin_images_path %>

app/views/admin/images/index.html.erb
<h1>Listing images</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Short description</th>
    <th>Description</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @images.each do |image| %>
  <tr>
    <td><%= image.name %></td>
    <td><%= image.short_description %></td>
    <td><%= image.url %></td>
    <td><%= link_to 'Show', [:admin,image] %></td>
    <td><%= link_to 'Edit', edit_admin_image_path(image) %></td>
    <td><%= link_to 'Destroy', [:admin,image], :confirm => 'Are you sure?', :method => :delete %>   


</td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Image', new_admin_image_path %>

app/views/admin/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_images_path %>

app/views/admin/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @image.name %>
</p>

<p>
  <b>Short description:</b>
  <%= @image.short_description %>
</p>



<p>
  <b>Url:</b>
  <%= @image.url %>
</p>


<%= link_to 'Edit', edit_admin_image_path(@image) %> |
<%= link_to 'Back', admin_images_path %>

app/views/admin/index.html.erb
yo 

app/views/admin/locations/index.html.erb
aloha world

app/views/admin/related_images/_related_image.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>
<li>
  <img class="related-img" src="<%=related.image.thumbnail%>" />
  <div class="related-input">
    <input type="hidden" name="vendor[related_images_attributes][][_destroy]" value=""/>  
    <input type="hidden" name="vendor[related_images_attributes][][id]" value="<%=related.id%>"/>  
    <input type="hidden" name="vendor[related_images_attributes][][image_id]" value="<%=related.image_id%>"/>  
    <input type="hidden" name="vendor[related_images_attributes][][rank]" value="<%=related.rank%>"/>  
  Title <br/><input size="50" type="text" value="<%=related.alt_title%>" name="vendor[related_images_attributes][][alt_title]"/>
  <br/>
  Caption <br> <input size="50" type="text" value="<%=related.alt_description%>" name="vendor[related_images_attributes][][alt_description]"/>
  </div>
  <a href="#" class="image-delete">Delete</a>
  <div class="clear">
  </div>
</li>

app/views/admin/related_images/_related_image_form.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>
<li>
  <img class="related-img" src="<%=related.image.thumbnail%>" />
  <div class="related-input">
    <%=f.hidden_field :_destroy%>
    <%=f.hidden_field :id%>
    <%=f.hidden_field :image_id%>
    <%=f.hidden_field :rank%>
    <%= f.label :alt_title,'Title' %><br />
    <%= f.text_field :alt_title %>
    <%= f.label :alt_description,'Caption' %><br />
    <%= f.text_field :alt_description %>

  </div>
  <a href="#" class="image-delete">Delete</a>
  <div class="clear">
  </div>
</li>

app/views/admin/vendors/_form.html.erb
 <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <script src="/javascripts/map.js" type="text/javascript"></script>

<%= form_for(["admin",@vendor]) do |f| %>
  <% if @vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% @vendor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :short_description %><br />
    <%= f.text_field :short_description %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
<table>
  <tr>
    <td>  
      <div class="field">
        <%= f.label :address %><br />
        <%= f.text_area :address, :cols=>30,:rows=>3 %>
        <input type="button" id="poplatlong" value="Populate Lat, Lon"/> 
      </div>
      <div class="field">
        <%= f.label :latitude %><br />
        <%= f.text_field :latitude %>
      </div>
      <div class="field">
        <%= f.label :longitude %><br />
        <%= f.text_field :longitude %>
      </div>
    </td>
    <td>
      <div id="map_canvas" style="width:300px; height:300px"></div> 
    </td>
  </tr>
</table>  
  <div class="field"> 
    <table>
      <tr>
        <td>
          <%= f.label "Available" %> <br/>
          <ul id="available-categories">
            <%=loop_all_categories do |category,level| %>
            <li><span class="level"><%="-"*level%></span><%=category.name%> <a class="add-category" href="#">Add</a> 
              <div class="hidden-value"><%= category.id%></div></li>
            <%end%>  
           
          </ul>  
        </td>
        <td>
          <%= f.label "Selected Categories" %> <br/>
          <div id="selected-categories">
              <%@vendor.categories.each do |category|%>
                
                <li><input name="vendor[category_ids][]" type="hidden" value="<%=category.id%>">
                    <%=category.name%>
                    
                    <a class="remove-category" href="#">remove</a>
                  </li>
              <%end%>
          </div>
        </td>
      </tr>
    </table>  
    
   
  
  </div>
  Drag an image from the left to the right.
<div id="gallery">
  <table>
    <tr>
      <td id="search-cell">
        <input type="text" value="" name="image_search"/>
        <input type="button" value="Search" />
        <ul id="image-results" class="connectedSortable">
          <%@images.each do |image|%>
          <li><img src="<%=image.thumbnail%>"><%=image.name%><div class="id hidden"><%=image.id%></div></li>
          <%end%>
          
        </ul>
      </td>
      <td>
    <div id="selected-div">
        <ol id="selected-images" class="connectedSortable">
          <%if @vendor.related_images.size == 0%>
            <li class="default">Drop Here</li>
          <%else%>        
            <%@vendor.related_images.each do |related|%>
                     <%= render :partial => "/admin/related_images/related_image", :locals => { :related=>related } %>
 
            <%end%>  
          <%end%>        

        </ol>
    </div>  
      </td>
    </tr>  
  </table>  
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/vendors/_vendor_image.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<li>
  <img class="related-img" src="<%=related.image.thumbnail%>" />
  <div class="related-input">
      <input type="hidden" name="vendor[related_images][][image_id]" value="<%=related.id%>"/>  

  Title <br/><input size="50" type="text" value="<%=related.alt_title%>" name="vendor[related_images][][alt_title]"/>
  <br/>
  Caption <br> <input size="50" type="text" value="<%=related.alt_description%>" name="vendor[related_images][][alt_text]"/>
  </div>
  <div class="clear">
  </div>
</li>

app/views/admin/vendors/edit.html.erb
<h1>Editing vendor</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin,@vendor] %> |
<%= link_to 'Back', admin_vendors_path %>

app/views/admin/vendors/index.html.erb
<h1>Listing vendors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Short description</th>
    <th>Description</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vendors.each do |vendor| %>
  <tr>
    <td><%= vendor.name %></td>
    <td><%= vendor.short_description %></td>
    <td><%= vendor.description %></td>
    <td><%= vendor.url %></td>
    <td><%= link_to 'Show', [:admin,vendor] %></td>
    <td><%= link_to 'Edit', edit_admin_vendor_path(vendor) %></td>
    <td><%= link_to 'Destroy', [:admin,vendor], :confirm => 'Are you sure?', :method => :delete %>   


</td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vendor', new_admin_vendor_path %>

app/views/admin/vendors/new.html.erb
<h1>New vendor</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_vendors_path %>

app/views/admin/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @vendor.name %>
</p>

<p>
  <b>Short description:</b>
  <%= @vendor.short_description %>
</p>

<p>
  <b>Description:</b>
  <%= @vendor.description %>
</p>

<p>
  <b>Url:</b>
  <%= @vendor.url %>
</p>


<%= link_to 'Edit', edit_admin_vendor_path(@vendor) %> |
<%= link_to 'Back', admin_vendors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fma2</title>
  <p class="notice"><%=notice%></p>
  <p class="alert"><%=alert%></p>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>